// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYTC5dLcv-p2E3cykKlm_6qe8cPYbKQjw',
    appId: '1:211421487201:web:0e0d8bc02689d9d1574a20',
    messagingSenderId: '211421487201',
    projectId: 'medicamentapplication',
    authDomain: 'medicamentapplication.firebaseapp.com',
    storageBucket: 'medicamentapplication.firebasestorage.app',
    measurementId: 'G-Z0SM5Z6HLC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRNofY3ItbGMem5ZYhfdxbS4PUk-flkk4',
    appId: '1:223207611288:android:a905dfaa69de0c5d31a9ed',
    messagingSenderId: '223207611288',
    projectId: 'gpayapp-1af47',
    storageBucket: 'gpayapp-1af47.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyFuxTWOE19368UcqrMIRfrdP6SjNzKYQ',
    appId: '1:211421487201:ios:e81043ae51b6fcf9574a20',
    messagingSenderId: '211421487201',
    projectId: 'medicamentapplication',
    storageBucket: 'medicamentapplication.firebasestorage.app',
    iosBundleId: 'com.example.gpayApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyFuxTWOE19368UcqrMIRfrdP6SjNzKYQ',
    appId: '1:211421487201:ios:e81043ae51b6fcf9574a20',
    messagingSenderId: '211421487201',
    projectId: 'medicamentapplication',
    storageBucket: 'medicamentapplication.firebasestorage.app',
    iosBundleId: 'com.example.gpayApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBYTC5dLcv-p2E3cykKlm_6qe8cPYbKQjw',
    appId: '1:211421487201:web:2f17921f45d3fbbd574a20',
    messagingSenderId: '211421487201',
    projectId: 'medicamentapplication',
    authDomain: 'medicamentapplication.firebaseapp.com',
    storageBucket: 'medicamentapplication.firebasestorage.app',
    measurementId: 'G-53F3HEWJ4T',
  );
}